### ISSUE TITLE
baseline

### ISSUE THREAD

**Issue by tu12306** [Ben-Louis/FisherPruning-Pytorch#6]
您好，仓库里没有baseline训练文件，请问您是怎么对照剪枝效果呢？baseline是这样子训练吗？
_base_ = [
    '../_base_/models/resnet50.py', '../_base_/datasets/cifar10_bs16.py',
    '../_base_/schedules/cifar10_bs128.py', '../_base_/default_runtime.py'
]

optimizer = dict(lr=0.004)
work_dir = "work_dirs/resnet50-baselilne"
load_from = "https://download.openmmlab.com/mmclassification/v0/resnet/resnet50_8xb32_in1k_20210831-ea4938fc.pth"

**Comment by Ben-Louis** [comment]
res50的baseline配置文件是https://github.com/open-mmlab/mmclassification/blob/master/configs/resnet/resnet50_8xb32_in1k.py

**Comment by tu12306** [comment]
好的，谢谢。像我这种用cifar10数据集做实验，原有resnet50_prunig中 load_from的权重文件pth是不是不合适了呢？

**Comment by Ben-Louis** [comment]
对的，原来的ckpt是imagenet训的，分类head的维度和cifar不一样。你可以按照 https://github.com/open-mmlab/mmclassification/blob/master/configs/resnet/resnet50_8xb16_cifar10.py 修改一下config，load_from 改成 https://download.openmmlab.com/mmclassification/v0/resnet/resnet50_b16x8_cifar10_20210528-f54bfad9.pth

**Comment by tu12306** [comment]
好的，谢谢~

**Comment by tu12306** [comment]
您好，我还有一个疑问 剪枝后微调时deploy from剪枝保存的哪个pth呢？目前您的代码是每轮的pth都保存了下来
微调后验证load from 又如何选择哪个剪枝保存下来的pth嘞
